# Generated by Django 2.1.7 on 2022-03-21 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220321_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 21, 11, 10, 15, 182933)),
        ),
    ]
